//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioApp.Models.Db.LotteryDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryUserSelectedTable
    {
        public int CountryUserId { get; set; }
        public int CountryId { get; set; }
        public int UserId { get; set; }
    
        public virtual CountryTable CountryTable { get; set; }
        public virtual CountryUserTable CountryUserTable { get; set; }
    }
}
