//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioApp.Models.Db.LotteryDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LotteryDbEntities : DbContext
    {
        public LotteryDbEntities()
            : base("name=LotteryDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CountryTable> CountryTables { get; set; }
        public DbSet<CountryUserSelectedTable> CountryUserSelectedTables { get; set; }
        public DbSet<CountryUserTable> CountryUserTables { get; set; }
    }
}
